// Loads the editable YAML files in src/data. Edit those files, not this one.
import { parse } from 'yaml';
import profileRaw from '../data/profile.yaml?raw';
import cvRaw from '../data/cv.yaml?raw';
import teachingRaw from '../data/teaching.yaml?raw';
import serviceRaw from '../data/service.yaml?raw';
import metricsJson from '../data/metrics.json';

export interface Link { label: string; url: string }
export interface TimelineItem { period: string; role: string; org: string; logo?: string; note?: string }

export interface Profile {
  name: string;
  title: string;
  affiliation: string;
  affiliationUrl: string;
  location: string;
  photo: string;
  tagline: string;
  bio: string[];
  research: { title: string; image?: string; text: string }[];
  contact: { address: string; emailUser: string; emailDomain: string; phone: string };
  cvUrl: string;
  links: Link[];
  memberships: { name: string; url: string; logo?: string }[];
}

export interface Cv {
  experience: TimelineItem[];
  education: TimelineItem[];
  awards: { year: string; title: string; venue: string; text: string }[];
}

export interface Teaching {
  courses: { period: string; title: string; kind: string; role: string; org: string }[];
  supervision: { period: string; name: string; topic: string; note?: string }[];
  theses: { title: string; text: string; references?: { text: string; url?: string }[] }[];
}

export interface Service {
  editorial: { period: string; role: string; venue: string; detail?: string; url?: string; certificate?: string }[];
  reviewer: string[];
}

// Generated by scripts/update-metrics.mjs; do not edit by hand.
export interface Metrics {
  scholar: { hIndex: number; citations: number; i10: number | null; updated: string | null };
  scopus: { hIndex: number; citations: number; documents: number | null; updated: string | null };
}

export const profile = parse(profileRaw) as Profile;
export const cv = parse(cvRaw) as Cv;
export const teaching = parse(teachingRaw) as Teaching;
export const service = parse(serviceRaw) as Service;
export const metrics = metricsJson as Metrics;
